stages:
  - lint
  - test

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip

lint:
  stage: lint
  image: python:3.12
  before_script:
    - pip install flake8
  script:
    - flake8 src tests

test:
  stage: test
  image: python:3.12
  before_script:
    - pip install -r requirements.txt
    - pip install pytest
  script:
    - pytest
  artifacts:
    when: always
    paths:
      - report.xml
    reports:
      junit: report.xml
